## Lab. 12

### Solve the following problem using Genetic Algorithms:


Problem: Weighted N-Queen Problem


You are given an N×N chessboard, and each cell of the board has an associated weight. Your task is to find a valid placement of N queens such that the total weight of the queens is maximized, and no two queens threaten each other.





In the traditional N-Queen Problem, the goal is to place N queens on an N×N chessboard in such a way that no two queens threaten each other. In this variation, we introduce weights to the queens and aim to find a placement that maximizes the total weight of the queens while satisfying the constraint of non-threatening positions.


Constraints:

1. There should be exactly one queen in each row and each column.
2. No two queens should be placed in the same diagonal, i.e., they should not threaten each other.
3. The placement should maximize the total weight of the queens.


Representation:

Use a permutation-based representation. Each permutation represents the column position of the queen for each row. 

For example, if N=4, a valid permutation [2, 4, 1, 3] indicates that the queen in the first row is placed in column 2, the queen in the second row is placed in column 4, and so on.


Genetic Algorithm Steps:

1. *Initialization*: Generate an initial population of permutations randomly.

2. *Fitness Evaluation*: Evaluate the fitness of each permutation by calculating the total weight of the queens while considering the non-threatening positions.

3. *Selection*: Select a subset of permutations from the population based on their fitness, using selection techniques like tournament selection or roulette wheel selection.

4. *Crossover*: Perform crossover (recombination) on the selected permutations to create new offspring permutations.

5. *Mutation*: Introduce random changes (mutations) in the offspring permutations to maintain diversity in the population.

6. *Fitness Evaluation for the new individuals*: Evaluate the fitness of the new population.

7. *Form the new population*: Select the surviving individuals based on scores, with chances direct proportional with their performance.

8. Repeat steps 3-7 for a certain number of generations or until a termination condition is met (e.g., a maximum number of iterations or a satisfactory solution is found).


9. *Termination*: Return the best-performing individual (permutation) found as the solution to the problem.

Note: The fitness function used in this problem should calculate the total weight of the queens based on the positions specified by the permutation. Additionally, the fitness function should penalize solutions that violate the non-threatening constraint by assigning a lower fitness score to such permutations.



In [2]:
import numpy as np
from random import shuffle, choice, randint

def generate_population(size, n):
    return [np.random.permutation(n) for _ in range(size)]

def fitness(perm, weights):
    n = len(perm)
    total_weight = sum(weights[i][perm[i]] for i in range(n))
    # Check for diagonal conflicts
    diag_conflicts = sum(1 for i in range(n) for j in range(i+1, n) if abs(i - j) == abs(perm[i] - perm[j]))
    # Penalize conflicts 
    return total_weight - diag_conflicts * 1000  

def select(population, weights, tournament_size=3):
    tournament = [choice(population) for _ in range(tournament_size)]
    tournament_fitness = [fitness(ind, weights) for ind in tournament]
    return tournament[np.argmax(tournament_fitness)]

def crossover(parent1, parent2):
    n = len(parent1)
    point = randint(0, n - 1)
    child = list(parent1[:point]) + list(parent2[point:])
    fix_permutation(child)
    return child

def fix_permutation(perm):
    seen = set(perm)
    missing = set(range(len(perm))) - seen
    seen_twice = [x for x in perm if perm.count(x) > 1]
    replace_map = dict(zip(seen_twice, missing))
    for i in range(len(perm)):
        if perm[i] in replace_map:
            perm[i] = replace_map.pop(perm[i])

def mutate(perm, mutation_rate=0.05):
    n = len(perm)
    if np.random.rand() < mutation_rate:
        i, j = np.random.randint(0, n, 2)
        perm[i], perm[j] = perm[j], perm[i]

def genetic_algorithm(weights, population_size=100, generations=1000):
    n = len(weights)
    population = generate_population(population_size, n)
    for _ in range(generations):
        new_population = []
        for _ in range(population_size):
            parent1 = select(population, weights)
            parent2 = select(population, weights)
            child = crossover(parent1, parent2)
            mutate(child)
            new_population.append(child)
        population = new_population
    best_individual = max(population, key=lambda x: fitness(x, weights))
    return best_individual

n = 8  # Board size
weights = np.random.randint(1, 10, (n, n))
print("Weights:")
print(weights)
print('\n')
best_solution = genetic_algorithm(weights)
print("Best solution:", best_solution)
print("Maximum weight:", fitness(best_solution, weights))


Weights:
[[3 9 6 8 9 5 8 2]
 [1 5 6 7 4 5 2 4]
 [4 9 4 8 8 4 7 6]
 [6 4 9 6 4 2 1 3]
 [5 6 6 8 9 2 8 5]
 [6 8 8 4 1 6 8 8]
 [2 1 4 4 4 6 7 1]
 [9 1 3 4 8 5 8 8]]
Best solution: [3, 1, 7, 5, 0, 2, 4, 6]
Maximum weight: 46
